# Generated by Django 5.0.7 on 2024-07-18 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='nome da categoria')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='related_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.user'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='media/{}', verbose_name='imagem'),
        ),
        migrations.AddField(
            model_name='product',
            name='related_category',
            field=models.ManyToManyField(to='home.category'),
        ),
    ]
